apiVersion: batch/v1
kind: Job
metadata:
  name: seed-database
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seed
          image: krassso/arknights-app:latest
          command: ["python", "-m", "app.seed"]
          env:
            - name: DATABASE_URL
              value: postgresql+psycopg2://arknights:arknights@postgres:5432/arknights
