apiVersion: v1
data:
  V1__create_tables.sql: ""
  V2__seed_initial_data.sql: "INSERT INTO operators (name, attack, damage_type) VALUES\r\n('Exusiai',
    650, 'physical'),\r\n('SilverAsh', 900, 'physical'),\r\n('Eyjafjalla', 800, 'arts'),\r\n('Surtr',
    2000, 'arts'),\r\n('Mlynar', 1800, 'physical'),\r\n('Mons3r', 1200, 'true'),\r\n('Saga',
    1000, 'physical'),\r\n('Bubble', 300, 'physical');\r\n\r\nINSERT INTO bosses (name,
    defense, resistance) VALUES\r\n('Patriot', 1200, 50),\r\n('FrostNova', 600, 70),\r\n('Crownslayer',
    400, 20),\r\n('Last Steam Knight', 2000, 10),\r\n('Minimalist', 200, 40),\r\n('Pompeii',
    200, 80),\r\n('Mechanist', 1400, 50);\r\n"
  V3__add_more_data.sql: "INSERT INTO operators (name, attack, damage_type) VALUES\r\n('Texas',
    750, 'physical'),\r\n('Bagpipe', 1100, 'physical'),\r\n('Ifrit', 950, 'arts'),\r\n('Ceobe',
    870, 'arts'),\r\n('Kal''tsit', 1300, 'true');\r\n\r\nINSERT INTO bosses (name,
    defense, resistance) VALUES\r\n('Talulah', 1800, 60),\r\n('Mephisto', 300, 90),\r\n('Skullshatterer',
    700, 25);"
  V4__add_more_operators.sql: "INSERT INTO operators (name, attack, damage_type) VALUES\r\n('Lappland',
    720, 'physical'),\r\n('Ifrit', 950, 'arts'),\r\n('Blaze', 1100, 'physical');\r\n"
kind: ConfigMap
metadata:
  name: flyway-migrations
