name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest flake8 bandit

      - name: Lint
        run: flake8 app tests

      - name: Security scan
        run: bandit -r app

      - name: Run tests
        run: pytest

      - name: Build Docker image
        run: docker build -t arknights-app:test .